### ISSUE TITLE
Release npm package with #26

### ISSUE THREAD

**Issue by stevenguh** [PAIR-code/scatter-gl#36]
The current version in the npm doesn't include the fix in #26. Is there any chance we can get an update on the npm with fix?

**Comment by cannoneyed** [comment]
Yup, sorry about that v0.0.4 should be published now!

**Comment by stevenguh** [comment]
I can't draw any lines with v0.0.4 released; however, I can with the scatter-gl lib (`https://storage.googleapis.com/learnjs-data/handtrack_staging/scatter-gl.js`) included in handpose demo. Maybe @annxingyuan the author of the handpose and PR #26 can chime in?

**Comment by stevenguh** [comment]
I figured out that, this is due to the three.js version somehow. Opened a new issue #40.
