### ISSUE TITLE
extra console.log?

### ISSUE THREAD

**Issue by radames** [PAIR-code/scatter-gl#55]
I just noticed a "console.log" left on latest commit of `scatter_plot.ts` ://github.com/PAIR-code/scatter-gl/commit/a9e8a816754d53ef573a38df9df7c4d58c7c329f#diff-9298a6445b2ddc4745fb5b8a7229a041b60594f3ea841df333e5d7d4fb4d3053R223
https://github.com/PAIR-code/scatter-gl/blob/345cf12f21c565b3abb2a77338de2ae28e317448/src/scatter_plot.ts#L223

It's not substantial! thanks

**Comment by cannoneyed** [comment]
Fixed in https://github.com/PAIR-code/scatter-gl/pull/64
