### ISSUE TITLE
"undefined" label in demo on 2D canvas select

### ISSUE THREAD

**Issue by DeNeutoy** [PAIR-code/scatter-gl#56]
Hello @cannoneyed!

This is a very nice little library, thanks for extracting this functionality from the main tensorflow projector. I'm finding it very useful in a project i'm working on. 

I found a small bug in the label rendering - when using a 2D canvas and points are selected, an "undefined" string label is also rendered at the same time. This occurs in the github pages demo also. I am not quite sure why this is happening, but two additional details:

1. the undefined label occurs on the very first point that is passed in the dataset
2. It only occurs for the canvas renderer, so I wonder if it is related to a 3d `ScatterPlotVisualizer` which is attached to the ScatterPlot, which is subsequently not removed when the renderer infers the dataset dimensionality. Also, [`disposeAllVisualizers`](https://github.com/PAIR-code/scatter-gl/blob/345cf12f21c565b3abb2a77338de2ae28e317448/src/scatter_plot.ts#L668) here is never called, I think.  

Anyway, thanks for the library - let me know if I can contribute a fix, if it's obvious to you what the problem is. Ta!

<img width="970" alt="Screen Shot 2021-02-02 at 11 25 06 AM" src="https://user-images.githubusercontent.com/16001974/106651706-64050280-6549-11eb-88a5-fa503d8cd042.png">

**Comment by joaorulff** [comment]
Any updates on this? :)

**Comment by joaorulff** [comment]
> Any updates on this? :)

Quick workaround: set label styles to 0.

**Comment by cannoneyed** [comment]
Hey! Just got pinged about this from another direction - I haven't checked on the library in a while but I think I can take a look at this soon.
