### ISSUE TITLE
Point Selection

### ISSUE THREAD

**Issue by joaorulff** [PAIR-code/scatter-gl#59]
Why not all points get selected when there is overlap between points? Is it possible to fix it? 
Example: 

Point selection when zoomed out:
<img width="1437" alt="Screen Shot 2021-03-16 at 11 51 05 AM" src="https://user-images.githubusercontent.com/7430591/111339504-30d88780-864e-11eb-9f1d-60f75408e544.png">

Points actually selected:
<img width="1436" alt="Screen Shot 2021-03-16 at 11 51 50 AM" src="https://user-images.githubusercontent.com/7430591/111339607-464db180-864e-11eb-914c-60774ba819a0.png">

Thanks for the lib. it's very helpful!

**Comment by cannoneyed** [comment]
Sorry I've been tied up with other projects - I'm not 100% sure what you're asking here but I'll do my best to try to look into it.
