### ISSUE TITLE
Render Mode - Sprites

### ISSUE THREAD

**Issue by murtazaqa** [PAIR-code/scatter-gl#60]
Hi,

Thank you for this very useful library.

I have a query regarding sprites render mode.

Currently, the number of small sprites present in the image should be equal to or more than the number of data points on the plot. Is there a way to reuse these sprites and avoid repetition?

I have repetitive images and want to reuse the same image for multiple coordinates.

Thanks.

**Comment by murtazaqa** [comment]
Hey @cannoneyed,

Would you mind looking at this query once?

Thanks.

**Comment by cannoneyed** [comment]
Hey sorry! I've been busy on a ton of other stuff. I'll take a look at this and see what I find.

**Comment by cannoneyed** [comment]
Alright, fixed in https://github.com/PAIR-code/scatter-gl/pull/63 - check out demo/index.ts for a commented out line on how to set sprite indices manually!
